kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bleep-cluster
# featureGates:
  # PodLifecycleSleepAction: true
nodes:
- role: control-plane
  image: kindest/node:latest
  kubeadmConfigPatches:
    - |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          v: "3"  # Set verbosity level here